<?php

namespace App;

use YAPF\DB_OBJECTS\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Alltypestable extends genClass
{
    protected $use_table = "alltypestable";
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "stringfield" => ["type" => "str", "value" => null],
        "intfield" => ["type" => "int", "value" => null],
        "floatfield" => ["type" => "float", "value" => null],
    ];
    public function getStringfield(): ?string
    {
        return $this->getField("stringfield");
    }
    public function getIntfield(): ?int
    {
        return $this->getField("intfield");
    }
    public function getFloatfield(): ?double
    {
        return $this->getField("floatfield");
    }
    public function setStringfield(?string $newvalue): array
    {
        return $this->updateField("stringfield", $newvalue);
    }
    public function setIntfield(?int $newvalue): array
    {
        return $this->updateField("intfield", $newvalue);
    }
    public function setFloatfield(?double $newvalue): array
    {
        return $this->updateField("floatfield", $newvalue);
    }
}
// please do not edit this file
