<?php

namespace YAPF\Junk\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;

// Do not edit this file, rerun gen.php to update!
class Flagedvalues extends genClass
{
    protected $use_table = "test.flagedvalues";
    // Data Design
    protected $fields = [
        "id",
        "name",
        "value",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "value" => ["type" => "str", "value" => null],
    ];
    // Setters
    /**
    * setName
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setName(?string $newvalue): array
    {
        return $this->updateField("name", $newvalue);
    }
    /**
    * setValue
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setValue(?string $newvalue): array
    {
        return $this->updateField("value", $newvalue);
    }
    // Getters
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getValue(): ?string
    {
        return $this->getField("value");
    }
    // Loaders
    public function loadByName(string $name): bool
    {
        return $this->loadByField(
            "name",
            $name
        );
    }
    public function loadByValue(string $value): bool
    {
        return $this->loadByField(
            "value",
            $value
        );
    }
}
// please do not edit this file
