<?php

namespace YAPF\Junk\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Junk\Sets\RelationtestingbSet as RelationtestingbSet;

// Do not edit this file, rerun gen.php to update!
class Relationtestinga extends genClass
{
    protected $use_table = "test.relationtestinga";
    // Data Design
    protected $fields = [
        "id",
        "name",
        "linkid",
    ];
    protected $dataset = [
        "id" => ["type" => "int", "value" => null],
        "name" => ["type" => "str", "value" => null],
        "linkid" => ["type" => "int", "value" => null],
    ];
    // Setters
    /**
    * setName
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setName(?string $newvalue): array
    {
        return $this->updateField("name", $newvalue);
    }
    /**
    * setLinkid
    * @return mixed[] [status =>  bool, message =>  string]
    */
    public function setLinkid(?int $newvalue): array
    {
        return $this->updateField("linkid", $newvalue);
    }
    // Getters
    public function getName(): ?string
    {
        return $this->getField("name");
    }
    public function getLinkid(): ?int
    {
        return $this->getField("linkid");
    }
    // Loaders
    public function loadByName(string $name): bool
    {
        return $this->loadByField(
            "name",
            $name
        );
    }
    public function loadByLinkid(int $linkid): bool
    {
        return $this->loadByField(
            "linkid",
            $linkid
        );
    }
    public function fetchRelatedRelationtestingbSet(): RelationtestingbSet
    {
        $ids = [$this->getLinkid()];
        $collection = new RelationtestingbSet();
        $collection->loadFromIds($ids);
        return $collection;
    }
}
// please do not edit this file
