<?php

namespace YAPF\Junk\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Junk\Sets\SchoolsSet as SchoolsSet;

// Do not edit this file, rerun gen.php to update!
class Schoolpendingcontact extends genClass
{
	protected $use_table = "test.schoolpendingcontact";
	// Data Design
	protected $fields = [
		"id",
		"schoolLink",
		"UID",
		"unixtime",
		"contactName",
		"contactEmail",
		"contactPhonenumber",
		"contactMessage",
		"sent",
		"messageviewed",
	];
	protected $dataset = [
		"id" => ["type" => "int", "value" => null],
		"schoolLink" => ["type" => "int", "value" => null],
		"UID" => ["type" => "str", "value" => null],
		"unixtime" => ["type" => "int", "value" => null],
		"contactName" => ["type" => "str", "value" => null],
		"contactEmail" => ["type" => "str", "value" => null],
		"contactPhonenumber" => ["type" => "str", "value" => null],
		"contactMessage" => ["type" => "str", "value" => null],
		"sent" => ["type" => "bool", "value" => 0],
		"messageviewed" => ["type" => "bool", "value" => 0],
	];
	// Setters
	/**
	* setSchoolLink
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setSchoolLink(?int $newvalue): array
	{
		return $this->updateField("schoolLink", $newvalue);
	}
	/**
	* setUID
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setUID(?string $newvalue): array
	{
		return $this->updateField("UID", $newvalue);
	}
	/**
	* setUnixtime
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setUnixtime(?int $newvalue): array
	{
		return $this->updateField("unixtime", $newvalue);
	}
	/**
	* setContactName
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setContactName(?string $newvalue): array
	{
		return $this->updateField("contactName", $newvalue);
	}
	/**
	* setContactEmail
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setContactEmail(?string $newvalue): array
	{
		return $this->updateField("contactEmail", $newvalue);
	}
	/**
	* setContactPhonenumber
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setContactPhonenumber(?string $newvalue): array
	{
		return $this->updateField("contactPhonenumber", $newvalue);
	}
	/**
	* setContactMessage
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setContactMessage(?string $newvalue): array
	{
		return $this->updateField("contactMessage", $newvalue);
	}
	/**
	* setSent
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setSent(?bool $newvalue): array
	{
		return $this->updateField("sent", $newvalue);
	}
	/**
	* setMessageviewed
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setMessageviewed(?bool $newvalue): array
	{
		return $this->updateField("messageviewed", $newvalue);
	}
	// Getters
	public function getSchoolLink(): ?int
	{
		return $this->getField("schoolLink");
	}
	public function getUID(): ?string
	{
		return $this->getField("UID");
	}
	public function getUnixtime(): ?int
	{
		return $this->getField("unixtime");
	}
	public function getContactName(): ?string
	{
		return $this->getField("contactName");
	}
	public function getContactEmail(): ?string
	{
		return $this->getField("contactEmail");
	}
	public function getContactPhonenumber(): ?string
	{
		return $this->getField("contactPhonenumber");
	}
	public function getContactMessage(): ?string
	{
		return $this->getField("contactMessage");
	}
	public function getSent(): ?bool
	{
		return $this->getField("sent");
	}
	public function getMessageviewed(): ?bool
	{
		return $this->getField("messageviewed");
	}
	// Loaders
	public function loadBySchoolLink(int $schoolLink): bool
	{
		return $this->loadByField(
			"schoolLink",
			$schoolLink
		);
	}
	public function loadByUID(string $UID): bool
	{
		return $this->loadByField(
			"UID",
			$UID
		);
	}
	public function loadByUnixtime(int $unixtime): bool
	{
		return $this->loadByField(
			"unixtime",
			$unixtime
		);
	}
	public function loadByContactName(string $contactName): bool
	{
		return $this->loadByField(
			"contactName",
			$contactName
		);
	}
	public function loadByContactEmail(string $contactEmail): bool
	{
		return $this->loadByField(
			"contactEmail",
			$contactEmail
		);
	}
	public function loadByContactPhonenumber(string $contactPhonenumber): bool
	{
		return $this->loadByField(
			"contactPhonenumber",
			$contactPhonenumber
		);
	}
	public function loadByContactMessage(string $contactMessage): bool
	{
		return $this->loadByField(
			"contactMessage",
			$contactMessage
		);
	}
	public function loadBySent(bool $sent): bool
	{
		return $this->loadByField(
			"sent",
			$sent
		);
	}
	public function loadByMessageviewed(bool $messageviewed): bool
	{
		return $this->loadByField(
			"messageviewed",
			$messageviewed
		);
	}
	public function relatedSchools(): SchoolsSet
	{
		$ids = [$this->getSchoolLink()];
		$collection = new SchoolsSet();
		$collection->loadFromIds($ids);
		return $collection;
	}
}
// please do not edit this file
