<?php

namespace YAPF\Junk\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Junk\Sets\SchoolsSet as SchoolsSet;
use YAPF\Junk\Sets\UsersSet as UsersSet;

// Do not edit this file, rerun gen.php to update!
class Schoolassignments extends genClass
{
	protected $use_table = "test.schoolassignments";
	// Data Design
	protected $fields = [
		"id",
		"uid",
		"userLink",
		"schoolLink",
		"isOwner",
	];
	protected $dataset = [
		"id" => ["type" => "int", "value" => null],
		"uid" => ["type" => "str", "value" => null],
		"userLink" => ["type" => "int", "value" => null],
		"schoolLink" => ["type" => "int", "value" => null],
		"isOwner" => ["type" => "bool", "value" => 0],
	];
	// Setters
	/**
	* setUid
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setUid(?string $newvalue): array
	{
		return $this->updateField("uid", $newvalue);
	}
	/**
	* setUserLink
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setUserLink(?int $newvalue): array
	{
		return $this->updateField("userLink", $newvalue);
	}
	/**
	* setSchoolLink
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setSchoolLink(?int $newvalue): array
	{
		return $this->updateField("schoolLink", $newvalue);
	}
	/**
	* setIsOwner
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setIsOwner(?bool $newvalue): array
	{
		return $this->updateField("isOwner", $newvalue);
	}
	// Getters
	public function getUid(): ?string
	{
		return $this->getField("uid");
	}
	public function getUserLink(): ?int
	{
		return $this->getField("userLink");
	}
	public function getSchoolLink(): ?int
	{
		return $this->getField("schoolLink");
	}
	public function getIsOwner(): ?bool
	{
		return $this->getField("isOwner");
	}
	// Loaders
	public function loadByUid(string $uid): bool
	{
		return $this->loadByField(
			"uid",
			$uid
		);
	}
	public function loadByUserLink(int $userLink): bool
	{
		return $this->loadByField(
			"userLink",
			$userLink
		);
	}
	public function loadBySchoolLink(int $schoolLink): bool
	{
		return $this->loadByField(
			"schoolLink",
			$schoolLink
		);
	}
	public function loadByIsOwner(bool $isOwner): bool
	{
		return $this->loadByField(
			"isOwner",
			$isOwner
		);
	}
	public function relatedSchools(): SchoolsSet
	{
		$ids = [$this->getSchoolLink()];
		$collection = new SchoolsSet();
		$collection->loadFromIds($ids);
		return $collection;
	}
	public function relatedUsers(): UsersSet
	{
		$ids = [$this->getUserLink()];
		$collection = new UsersSet();
		$collection->loadFromIds($ids);
		return $collection;
	}
}
// please do not edit this file
