<?php

namespace YAPF\Junk\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Junk\Sets\SchoolassignmentsSet as SchoolassignmentsSet;
use YAPF\Junk\Sets\SchoolmapsSet as SchoolmapsSet;
use YAPF\Junk\Sets\SchoolpendingcontactSet as SchoolpendingcontactSet;
use YAPF\Junk\Sets\SchoolvideosSet as SchoolvideosSet;
use YAPF\Junk\Sets\SchoolviewsSet as SchoolviewsSet;

// Do not edit this file, rerun gen.php to update!
class Schools extends genClass
{
	protected $use_table = "test.schools";
	// Data Design
	protected $fields = [
		"id",
		"UID",
		"name",
		"disabled",
		"tourURL",
		"emailAddress",
	];
	protected $dataset = [
		"id" => ["type" => "int", "value" => null],
		"UID" => ["type" => "str", "value" => null],
		"name" => ["type" => "str", "value" => null],
		"disabled" => ["type" => "bool", "value" => 0],
		"tourURL" => ["type" => "str", "value" => null],
		"emailAddress" => ["type" => "str", "value" => null],
	];
	// Setters
	/**
	* setUID
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setUID(?string $newvalue): array
	{
		return $this->updateField("UID", $newvalue);
	}
	/**
	* setName
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setName(?string $newvalue): array
	{
		return $this->updateField("name", $newvalue);
	}
	/**
	* setDisabled
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setDisabled(?bool $newvalue): array
	{
		return $this->updateField("disabled", $newvalue);
	}
	/**
	* setTourURL
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setTourURL(?string $newvalue): array
	{
		return $this->updateField("tourURL", $newvalue);
	}
	/**
	* setEmailAddress
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setEmailAddress(?string $newvalue): array
	{
		return $this->updateField("emailAddress", $newvalue);
	}
	// Getters
	public function getUID(): ?string
	{
		return $this->getField("UID");
	}
	public function getName(): ?string
	{
		return $this->getField("name");
	}
	public function getDisabled(): ?bool
	{
		return $this->getField("disabled");
	}
	public function getTourURL(): ?string
	{
		return $this->getField("tourURL");
	}
	public function getEmailAddress(): ?string
	{
		return $this->getField("emailAddress");
	}
	// Loaders
	public function loadByUID(string $UID): bool
	{
		return $this->loadByField(
			"UID",
			$UID
		);
	}
	public function loadByName(string $name): bool
	{
		return $this->loadByField(
			"name",
			$name
		);
	}
	public function loadByDisabled(bool $disabled): bool
	{
		return $this->loadByField(
			"disabled",
			$disabled
		);
	}
	public function loadByTourURL(string $tourURL): bool
	{
		return $this->loadByField(
			"tourURL",
			$tourURL
		);
	}
	public function loadByEmailAddress(string $emailAddress): bool
	{
		return $this->loadByField(
			"emailAddress",
			$emailAddress
		);
	}
	public function relatedSchoolassignments(): SchoolassignmentsSet
	{
		$ids = [$this->getId()];
		$collection = new SchoolassignmentsSet();
		$collection->loadFromSchoolLinks($ids);
		return $collection;
	}
	public function relatedSchoolmaps(): SchoolmapsSet
	{
		$ids = [$this->getId()];
		$collection = new SchoolmapsSet();
		$collection->loadFromSchoolLinks($ids);
		return $collection;
	}
	public function relatedSchoolpendingcontact(): SchoolpendingcontactSet
	{
		$ids = [$this->getId()];
		$collection = new SchoolpendingcontactSet();
		$collection->loadFromSchoolLinks($ids);
		return $collection;
	}
	public function relatedSchoolvideos(): SchoolvideosSet
	{
		$ids = [$this->getId()];
		$collection = new SchoolvideosSet();
		$collection->loadFromSchoolLinks($ids);
		return $collection;
	}
	public function relatedSchoolviews(): SchoolviewsSet
	{
		$ids = [$this->getId()];
		$collection = new SchoolviewsSet();
		$collection->loadFromSchoolLinks($ids);
		return $collection;
	}
}
// please do not edit this file
