<?php

namespace YAPF\Junk\Models;

use YAPF\DbObjects\GenClass\GenClass as GenClass;
use YAPF\Junk\Sets\SchoolassignmentsSet as SchoolassignmentsSet;

// Do not edit this file, rerun gen.php to update!
class Users extends genClass
{
	protected $use_table = "test.users";
	// Data Design
	protected $fields = [
		"id",
		"googleemail",
		"disabled",
		"lhash",
		"systemop",
	];
	protected $dataset = [
		"id" => ["type" => "int", "value" => null],
		"googleemail" => ["type" => "str", "value" => null],
		"disabled" => ["type" => "bool", "value" => 0],
		"lhash" => ["type" => "str", "value" => null],
		"systemop" => ["type" => "bool", "value" => 0],
	];
	// Setters
	/**
	* setGoogleemail
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setGoogleemail(?string $newvalue): array
	{
		return $this->updateField("googleemail", $newvalue);
	}
	/**
	* setDisabled
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setDisabled(?bool $newvalue): array
	{
		return $this->updateField("disabled", $newvalue);
	}
	/**
	* setLhash
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setLhash(?string $newvalue): array
	{
		return $this->updateField("lhash", $newvalue);
	}
	/**
	* setSystemop
	* @return mixed[] [status =>  bool, message =>  string]
	*/
	public function setSystemop(?bool $newvalue): array
	{
		return $this->updateField("systemop", $newvalue);
	}
	// Getters
	public function getGoogleemail(): ?string
	{
		return $this->getField("googleemail");
	}
	public function getDisabled(): ?bool
	{
		return $this->getField("disabled");
	}
	public function getLhash(): ?string
	{
		return $this->getField("lhash");
	}
	public function getSystemop(): ?bool
	{
		return $this->getField("systemop");
	}
	// Loaders
	public function loadByGoogleemail(string $googleemail): bool
	{
		return $this->loadByField(
			"googleemail",
			$googleemail
		);
	}
	public function loadByDisabled(bool $disabled): bool
	{
		return $this->loadByField(
			"disabled",
			$disabled
		);
	}
	public function loadByLhash(string $lhash): bool
	{
		return $this->loadByField(
			"lhash",
			$lhash
		);
	}
	public function loadBySystemop(bool $systemop): bool
	{
		return $this->loadByField(
			"systemop",
			$systemop
		);
	}
	public function relatedSchoolassignments(): SchoolassignmentsSet
	{
		$ids = [$this->getId()];
		$collection = new SchoolassignmentsSet();
		$collection->loadFromUserLinks($ids);
		return $collection;
	}
}
// please do not edit this file
