<?php

namespace YAPF\Junk\Sets;

use YAPF\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use YAPF\Junk\Models\Alltypestable as Alltypestable;

// Do not edit this file, rerun gen.php to update!
class AlltypestableSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("YAPF\Junk\Models\Alltypestable");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Alltypestable
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Alltypestable
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Alltypestable
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Alltypestable
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueStringfields
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueStringfields(): array
    {
        return parent::uniqueArray("stringfield");
    }
    /**
     * uniqueIntfields
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIntfields(): array
    {
        return parent::uniqueArray("intfield");
    }
    /**
     * uniqueFloatfields
     * returns unique values from the collection matching that field
     * @return array<float>
     */
    public function uniqueFloatfields(): array
    {
        return parent::uniqueArray("floatfield");
    }
    /**
     * uniqueBoolfields
     * returns unique values from the collection matching that field
     * @return array<bool>
     */
    public function uniqueBoolfields(): array
    {
        return parent::uniqueArray("boolfield");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByStringfield
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByStringfield(
        string $stringfield, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "stringfield", 
            $stringfield, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromStringfields
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromStringfields(array $values): array
    {
        return $this->loadIndexs("stringfield", $values);
    }
    /**
     * loadByIntfield
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByIntfield(
        int $intfield, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "intfield", 
            $intfield, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIntfields
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIntfields(array $values): array
    {
        return $this->loadIndexs("intfield", $values);
    }
    /**
     * loadByFloatfield
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByFloatfield(
        float $floatfield, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "floatfield", 
            $floatfield, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromFloatfields
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromFloatfields(array $values): array
    {
        return $this->loadIndexs("floatfield", $values);
    }
    /**
     * loadByBoolfield
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByBoolfield(
        bool $boolfield, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "boolfield", 
            $boolfield, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromBoolfields
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromBoolfields(array $values): array
    {
        return $this->loadIndexs("boolfield", $values);
    }
    // Related loaders
}
