<?php

namespace YAPF\Junk\Sets;

use YAPF\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use YAPF\Junk\Models\Users as Users;

// Do not edit this file, rerun gen.php to update!
class UsersSet extends CollectionSet
{
	public function __construct()
	{
		parent::__construct("YAPF\Junk\Models\Users");
	}
	/**
	 * getObjectByID
	 * returns a object that matchs the selected id
	 * returns null if not found
	 * Note: Does not support bad Ids please use findObjectByField
	 */
	public function getObjectByID($id): ?Users
	{
		return parent::getObjectByID($id);
	}
	/**
	 * getFirst
	 * returns the first object in a collection
	 */
	public function getFirst(): ?Users
	{
		return parent::getFirst();
	}
	/**
	 * getObjectByField
	 * returns the first object in a collection that matchs the field and value checks
	 */
	public function getObjectByField(string $fieldname, $value): ?Users
	{
		return parent::getObjectByField($fieldname, $value);
	}
	/**
	 * current
	 * used by foreach to get the object should not be called directly
	 */
	public function current(): Users
	{
		return parent::current();
	}
	/**
	 * uniqueIds
	 * returns unique values from the collection matching that field
	 * @return array<int>
	 */
	public function uniqueIds(): array
	{
		return parent::uniqueArray("id");
	}
	/**
	 * uniqueGoogleemails
	 * returns unique values from the collection matching that field
	 * @return array<string>
	 */
	public function uniqueGoogleemails(): array
	{
		return parent::uniqueArray("googleemail");
	}
	/**
	 * uniqueDisableds
	 * returns unique values from the collection matching that field
	 * @return array<bool>
	 */
	public function uniqueDisableds(): array
	{
		return parent::uniqueArray("disabled");
	}
	/**
	 * uniqueLhashs
	 * returns unique values from the collection matching that field
	 * @return array<string>
	 */
	public function uniqueLhashs(): array
	{
		return parent::uniqueArray("lhash");
	}
	/**
	 * uniqueSystemops
	 * returns unique values from the collection matching that field
	 * @return array<bool>
	 */
	public function uniqueSystemops(): array
	{
		return parent::uniqueArray("systemop");
	}
	// Loaders
	/**
	 * loadById
	 * @return mixed[] [status =>  bool, count => integer, message =>  string]
	*/
	public function loadById(
		int $id, 
		int $limit = 0, 
		string $orderBy = "id", 
		string $orderDir = "DESC"
	): array
	{
		return $this->loadByField(
			"id", 
			$id, 
			$limit, 
			$orderBy, 
			$orderDir
		);
	}
	/**
	 * loadFromIds
	 * @return array<mixed> [status =>  bool, count => integer, message =>  string]
	*/
	public function loadFromIds(array $values): array
	{
		return $this->loadIndexs("id", $values);
	}
	/**
	 * loadByGoogleemail
	 * @return mixed[] [status =>  bool, count => integer, message =>  string]
	*/
	public function loadByGoogleemail(
		string $googleemail, 
		int $limit = 0, 
		string $orderBy = "id", 
		string $orderDir = "DESC"
	): array
	{
		return $this->loadByField(
			"googleemail", 
			$googleemail, 
			$limit, 
			$orderBy, 
			$orderDir
		);
	}
	/**
	 * loadFromGoogleemails
	 * @return array<mixed> [status =>  bool, count => integer, message =>  string]
	*/
	public function loadFromGoogleemails(array $values): array
	{
		return $this->loadIndexs("googleemail", $values);
	}
	/**
	 * loadByDisabled
	 * @return mixed[] [status =>  bool, count => integer, message =>  string]
	*/
	public function loadByDisabled(
		bool $disabled, 
		int $limit = 0, 
		string $orderBy = "id", 
		string $orderDir = "DESC"
	): array
	{
		return $this->loadByField(
			"disabled", 
			$disabled, 
			$limit, 
			$orderBy, 
			$orderDir
		);
	}
	/**
	 * loadFromDisableds
	 * @return array<mixed> [status =>  bool, count => integer, message =>  string]
	*/
	public function loadFromDisableds(array $values): array
	{
		return $this->loadIndexs("disabled", $values);
	}
	/**
	 * loadByLhash
	 * @return mixed[] [status =>  bool, count => integer, message =>  string]
	*/
	public function loadByLhash(
		string $lhash, 
		int $limit = 0, 
		string $orderBy = "id", 
		string $orderDir = "DESC"
	): array
	{
		return $this->loadByField(
			"lhash", 
			$lhash, 
			$limit, 
			$orderBy, 
			$orderDir
		);
	}
	/**
	 * loadFromLhashs
	 * @return array<mixed> [status =>  bool, count => integer, message =>  string]
	*/
	public function loadFromLhashs(array $values): array
	{
		return $this->loadIndexs("lhash", $values);
	}
	/**
	 * loadBySystemop
	 * @return mixed[] [status =>  bool, count => integer, message =>  string]
	*/
	public function loadBySystemop(
		bool $systemop, 
		int $limit = 0, 
		string $orderBy = "id", 
		string $orderDir = "DESC"
	): array
	{
		return $this->loadByField(
			"systemop", 
			$systemop, 
			$limit, 
			$orderBy, 
			$orderDir
		);
	}
	/**
	 * loadFromSystemops
	 * @return array<mixed> [status =>  bool, count => integer, message =>  string]
	*/
	public function loadFromSystemops(array $values): array
	{
		return $this->loadIndexs("systemop", $values);
	}
	// Related loaders
	public function relatedSchoolassignments(): SchoolassignmentsSet
	{
		$ids = $this->uniqueIds();
		$collection = new SchoolassignmentsSet();
		$collection->loadFromUserLinks($ids);
		return $collection;
	}
}
