<?php

namespace YAPF\Junk\Sets;

use YAPF\DbObjects\CollectionSet\CollectionSet as CollectionSet;
use YAPF\Junk\Models\Weirdtable as Weirdtable;

// Do not edit this file, rerun gen.php to update!
class WeirdtableSet extends CollectionSet
{
    public function __construct()
    {
        parent::__construct("YAPF\Junk\Models\Weirdtable");
    }
    /**
     * getObjectByID
     * returns a object that matchs the selected id
     * returns null if not found
     * Note: Does not support bad Ids please use findObjectByField
     */
    public function getObjectByID($id): ?Weirdtable
    {
        return parent::getObjectByID($id);
    }
    /**
     * getFirst
     * returns the first object in a collection
     */
    public function getFirst(): ?Weirdtable
    {
        return parent::getFirst();
    }
    /**
     * getObjectByField
     * returns the first object in a collection that matchs the field and value checks
     */
    public function getObjectByField(string $fieldname, $value): ?Weirdtable
    {
        return parent::getObjectByField($fieldname, $value);
    }
    /**
     * current
     * used by foreach to get the object should not be called directly
     */
    public function current(): Weirdtable
    {
        return parent::current();
    }
    /**
     * uniqueIds
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueIds(): array
    {
        return parent::uniqueArray("id");
    }
    /**
     * uniqueWeirdas
     * returns unique values from the collection matching that field
     * @return array<string>
     */
    public function uniqueWeirdas(): array
    {
        return parent::uniqueArray("weirda");
    }
    /**
     * uniqueWeirdbs
     * returns unique values from the collection matching that field
     * @return array<int>
     */
    public function uniqueWeirdbs(): array
    {
        return parent::uniqueArray("weirdb");
    }
    // Loaders
    /**
     * loadById
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadById(
        int $id, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "id", 
            $id, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromIds
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromIds(array $values): array
    {
        return $this->loadIndexs("id", $values);
    }
    /**
     * loadByWeirda
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByWeirda(
        string $weirda, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "weirda", 
            $weirda, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromWeirdas
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromWeirdas(array $values): array
    {
        return $this->loadIndexs("weirda", $values);
    }
    /**
     * loadByWeirdb
     * @return mixed[] [status =>  bool, count => integer, message =>  string]
    */
    public function loadByWeirdb(
        int $weirdb, 
        int $limit = 0, 
        string $orderBy = "id", 
        string $orderDir = "DESC"
    ): array
    {
        return $this->loadByField(
            "weirdb", 
            $weirdb, 
            $limit, 
            $orderBy, 
            $orderDir
        );
    }
    /**
     * loadFromWeirdbs
     * @return array<mixed> [status =>  bool, count => integer, message =>  string]
    */
    public function loadFromWeirdbs(array $values): array
    {
        return $this->loadIndexs("weirdb", $values);
    }
    // Related loaders
}
