<?php

namespace YAPF\Framework\Generator;

class SetObjectFactory extends Shared
{
    public function __construct(
        protected string $dbName,
        protected array $tables,
        protected array $links,
        protected bool $prefixDb,
        protected string $namespace,
        protected string $saveToFolder,
        protected array $ignoreTables
    ) {
        parent::__construct();
        $this->corenamespace = $this->namespace;
        $this->namespace = str_replace("<!DBName!>", $this->dbName, $this->namespace);
        $this->namespace = str_replace("(Set)", "/Set", $this->namespace);
        $this->namespaceSingle = str_replace("/Set", "", $this->namespace);
        $this->namespaceSingle = str_replace("/", "\\\\", $this->namespaceSingle);
        $this->namespace = str_replace("/", "\\", $this->namespace);
        $this->namespaceSet = str_replace("(Set)", "\\Set", $this->namespace);
        $this->saveToFolder = str_replace("(Set)", "Set/", $this->saveToFolder);
        $this->saveToFolder = str_replace("<!DBName!>", $this->dbName . "/", $this->saveToFolder);
        foreach ($this->tables[$this->dbName] as $table) {
            if (in_array($table["TABLE_NAME"], $this->ignoreTables) == true) {
                continue;
            }
            $this->createClass($table["TABLE_NAME"]);
        }
    }

    protected function createClass(string $table): void
    {
        $this->className = ucfirst(strtolower($table));
        $this->filename = $this->className . "Set.php";
        $this->workingTable = $table;
        $this->lines = [];
        $this->cols = $this->getTableColumns($this->dbName, $this->workingTable);
        $this->createModelHeader();
        $this->createModelDataset();
        $this->createModelSetters();
        $this->createModelGetters();
        $this->createModelLoaders();
        $this->createRelatedLoaders();
        $this->createModelFooter();
        $this->writeFile($this->lines2text(), $this->filename, $this->saveToFolder);
    }

    public function getRelatedCounter(): int
    {
        return count($this->seenRelated);
    }
    protected array $seenRelated = [];
    protected function createModelHeader(): void
    {
        $useWorker = str_replace("\\\\", "\\", $this->namespaceSingle);
        $this->lines[] = '<?php';
        $this->lines[] = '';
        $this->lines[] = 'namespace ' . $this->namespaceSet . ';';
        $this->lines[] = '';
        $this->lines[] = 'use YAPF\Framework\Responses\DbObjects\SetsLoadReply as SetsLoadReply;';
        $this->lines[] = 'use YAPF\Framework\DbObjects\CollectionSet\CollectionSet as CollectionSet;';
        $this->lines[] = 'use ' . $useWorker . '\\' . $this->className . ' as ' . $this->className . ';';
        $seenused = [];
        foreach ($this->links as $entry) {
            $targetClass = "";
            $targetDb = "";
            if ($entry["sourceTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["targetTable"]));
                $targetDb = $entry["targetDatabase"];
            } elseif ($entry["targetTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["sourceTable"]));
                $targetDb = $entry["sourceDatabase"];
            }
            if ($targetClass == "") {
                continue;
            }
            $targetClassName =  $targetClass;
            if (in_array($targetClassName, $seenused) == true) {
                continue;
            }
            $dbnameprefix = ucfirst(strtolower($targetDb));
            $seenused[] = $targetClassName;
            $namespace = $this->corenamespace;
            $namespace = str_replace("(Set)", "\Set", $namespace);
            $namespace = str_replace("<!DBName!>", $targetDb, $namespace);
            $namespace = str_replace("/", "\\", $namespace);
            $this->lines[] = 'use ' . $namespace . '\\'
            . $targetClass . 'Set as ' . $dbnameprefix . '' . $targetClass . ';';
        }


        $this->lines[] = '';
        $this->lines[] = '// Do not edit this file, rerun gen.php to update!';
        $this->lines[] = 'class ' . $this->className . 'Set extends CollectionSet';
        $this->lines[] = '{';
        $this->lines[] = [1];
        $this->lines[] = 'public function __construct()';
        $this->lines[] = '{';
        $this->lines[] = [2];
        $this->lines[] = 'parent::__construct("' . $this->namespaceSingle . '\\\\' . $this->className . '");';
        $this->lines[] = [1];
        $this->lines[] = '}';
        $this->lines[] = [1];
    }

    protected function createModelDataset(): void
    {
        // Not used
    }

    protected function createModelSetters(): void
    {
        // Not used
    }

    protected function createModelGetters(): void
    {
        $this->lines[] = '/**';
        $this->lines[] = ' * getObjectByID';
        $this->lines[] = ' * returns a object that matchs the selected id';
        $this->lines[] = ' * returns null if not found';
        $this->lines[] = ' * Note: Does not support bad Ids please use findObjectByField';
        $this->lines[] = ' */';
        $this->lines[] = 'public function getObjectByID($id): ?' . $this->className . '';
        $this->lines[] = '{';
        $this->lines[] = [2];
        $this->lines[] = 'return parent::getObjectByID($id);';
        $this->lines[] = [1];
        $this->lines[] = '}';
        $this->lines[] = '/**';
        $this->lines[] = ' * getFirst';
        $this->lines[] = ' * returns the first object in a collection';
        $this->lines[] = ' */';
        $this->lines[] = 'public function getFirst(): ?' . $this->className . '';
        $this->lines[] = '{';
        $this->lines[] = [2];
        $this->lines[] = 'return parent::getFirst();';
        $this->lines[] = [1];
        $this->lines[] = '}';
        $this->lines[] = '/**';
        $this->lines[] = ' * getObjectByField';
        $this->lines[] = ' * returns the first object in a collection that matchs the field and value checks';
        $this->lines[] = ' */';
        $this->lines[] = 'public function getObjectByField(string $fieldName, $value): ?' . $this->className . '';
        $this->lines[] = '{';
        $this->lines[] = [2];
        $this->lines[] = 'return parent::getObjectByField($fieldName, $value);';
        $this->lines[] = [1];
        $this->lines[] = '}';
        $this->lines[] = '/**';
        $this->lines[] = ' * current';
        $this->lines[] = ' * used by foreach to get the object should not be called directly';
        $this->lines[] = ' */';
        $this->lines[] = 'public function current(): ' . $this->className . '';
        $this->lines[] = '{';
        $this->lines[] = [2];
        $this->lines[] = 'return parent::current();';
        $this->lines[] = [1];
        $this->lines[] = '}';

        foreach ($this->cols as $rowTwo) {
            $useType = $this->getColType(
                $rowTwo["DATA_TYPE"],
                $rowTwo["COLUMN_TYPE"],
                $this->workingTable,
                $rowTwo["COLUMN_NAME"]
            );
            if ($useType == "str") {
                $useType = "string";
            }
            $functionName = "unique" . ucfirst($rowTwo["COLUMN_NAME"]) . "s";
            $this->lines[] = '/**';
            $this->lines[] = ' * ' . $functionName . '';
            $this->lines[] = ' * returns unique values from the collection matching that field';
            $this->lines[] = ' * @return array<' . $useType . '>';
            $this->lines[] = ' */';
            $this->lines[] = 'public function ' . $functionName . '(): array';
            $this->lines[] = '{';
            $this->lines[] = [2];
            $this->lines[] = 'return parent::uniqueArray("' . $rowTwo["COLUMN_NAME"] . '");';
            $this->lines[] = [1];
            $this->lines[] = '}';
        }
    }

    protected function createModelLoaders(): void
    {
        $this->lines[] = "// Loaders";
        foreach ($this->cols as $rowTwo) {
            $useType = $this->getColType(
                $rowTwo["DATA_TYPE"],
                $rowTwo["COLUMN_TYPE"],
                $this->workingTable,
                $rowTwo["COLUMN_NAME"]
            );
            if ($useType == "str") {
                $useType = "string";
            }
            $functionLoadName = 'loadBy' . ucfirst($rowTwo["COLUMN_NAME"]);

            $this->lines[] = '/**';
            $this->lines[] = ' * ' . $functionLoadName;
            $this->lines[] = '*/';
            $this->lines[] = 'public function ' . $functionLoadName . '(';
            $this->lines[] = [2];
            $this->lines[] = $useType . ' $' . $rowTwo["COLUMN_NAME"] . ',';
            $this->lines[] = 'int $limit = 0,';
            $this->lines[] = 'string $orderBy = "id",';
            $this->lines[] = 'string $orderDir = "DESC"';
            $this->lines[] = [1];
            $this->lines[] = '): SetsLoadReply {';
            $this->lines[] = [2];
            $this->lines[] = 'return $this->loadOnField(';
            $this->lines[] = [3];
            $this->lines[] = '"' . $rowTwo["COLUMN_NAME"] . '",';
            $this->lines[] = '$' . $rowTwo["COLUMN_NAME"] . ',';
            $this->lines[] = '$limit,';
            $this->lines[] = '$orderBy,';
            $this->lines[] = '$orderDir';
            $this->lines[] = [2];
            $this->lines[] =  ');';
            $this->lines[] = [1];
            $this->lines[] = '}';

            $functionLoadName = 'loadFrom' . ucfirst($rowTwo["COLUMN_NAME"]) . 's';

            $this->lines[] = '/**';
            $this->lines[] = ' * ' . $functionLoadName;
            $this->lines[] = '*/';
            $this->lines[] = 'public function ' . $functionLoadName . '(array $values): SetsLoadReply';
            $this->lines[] = '{';
            $this->lines[] = [2];
            $this->lines[] = 'return $this->loadIndexes("' . $rowTwo["COLUMN_NAME"] . '", $values);';
            $this->lines[] = [1];
            $this->lines[] = '}';
        }
    }

    protected function createRelatedLoaders(): void
    {
        $this->lines[] = '// Related loaders';
        $this->seenRelated = [];
        foreach ($this->links as $entry) {
            $targetClass = "";
            $fromField = "";
            $loadField = "";
            $targetDb = "";
            if ($entry["sourceTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["targetTable"]));
                $targetDb = $entry["targetDatabase"];
                $fromField = ucfirst($entry["sourceField"]);
                $loadField = ucfirst($entry["targetField"]);
            } elseif ($entry["targetTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["sourceTable"]));
                $targetDb = $entry["sourceDatabase"];
                $fromField = ucfirst($entry["targetField"]);
                $loadField = ucfirst($entry["sourceField"]);
            }
            if ($targetClass == "") {
                continue;
            }
            $dbnameprefix = ucfirst(strtolower($targetDb));
            $targetClassName =  $dbnameprefix . '' . $targetClass;
            if (in_array($targetClassName, $this->seenRelated) == true) {
                continue;
            }

            $this->seenRelated[] = $targetClassName;
            $this->lines[] = 'public function related' . $targetClass . '(?array $limitFields=null): ' .
            $targetClassName;
            $this->lines[] = '{';
            $this->lines[] = [2];
            $this->lines[] = '$ids = $this->unique' . $fromField . 's();';
            $this->lines[] = '$collection = new ' . $targetClassName . '();';
            $this->lines[] = 'if($limitFields !== null) {';
            $this->lines[] = [3];
            $this->lines[] = '$collection->limitFields($limitFields);';
            $this->lines[] = [2];
            $this->lines[] = '}';
            $this->lines[] = '$collection->loadFrom' . $loadField . 's($ids);';
            $this->lines[] = 'return $collection;';
            $this->lines[] = [1];
            $this->lines[] = '}';
        }
    }

    protected function createModelFooter(): void
    {
        $this->lines[] = [0];
        $this->lines[] = '}';
    }
}
