<?php

namespace YAPF\Framework\Generator;

class SingleObjectFactory extends Shared
{
    public function __construct(
        protected string $dbName,
        protected array $tables,
        protected array $links,
        protected bool $prefixDb,
        protected string $namespace,
        protected string $saveToFolder,
        protected array $ignoreTables
    ) {
        parent::__construct();
        $this->corenamespace = $this->namespace;
        $this->namespace = str_replace("<!DBName!>", $this->dbName, $this->namespace);
        $this->namespace = str_replace("(Set)", "", $this->namespace);
        $this->namespace = str_replace("/", "\\", $this->namespace);
        $this->namespaceSet = str_replace("(Set)", "\\Set", $namespace);
        $this->namespaceSet = str_replace("<!DBName!>", $this->dbName, $this->namespaceSet);
        $this->namespaceSet = str_replace("/", "\\", $this->namespaceSet);
        $this->saveToFolder = str_replace("(Set)", "", $this->saveToFolder);
        $this->saveToFolder = str_replace("<!DBName!>", $this->dbName . "/", $this->saveToFolder);
        foreach ($this->tables[$this->dbName] as $table) {
            if (in_array($table["TABLE_NAME"], $this->ignoreTables) == true) {
                continue;
            }
            $this->createClass($table["TABLE_NAME"]);
        }
    }

    protected function createClass(string $table): void
    {
        $this->className = ucfirst(strtolower($table));
        $this->filename = $this->className . ".php";
        $this->workingTable = $table;
        $this->lines = [];
        $this->cols = $this->getTableColumns($this->dbName, $this->workingTable);
        $this->createModelHeader();
        $this->createModelDataset();
        $this->createModelSetters();
        $this->createModelGetters();
        $this->createModelLoaders();
        $this->createRelatedLoaders();
        $this->createModelFooter();
        $this->writeFile($this->lines2text(), $this->filename, $this->saveToFolder);
    }

    public function getRelatedCounter(): int
    {
        return count($this->seenRelated);
    }
    protected array $seenRelated = [];
    protected function createRelatedLoaders(): void
    {
        $this->seenRelated = [];
        foreach ($this->links as $entry) {
            $targetClass = "";
            $fromField = "";
            $loadField = "";
            $targetDb = "";
            if ($entry["sourceTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["targetTable"]));
                $fromField = ucfirst($entry["sourceField"]);
                $loadField = ucfirst($entry["targetField"]);
                $targetDb = $entry["targetDatabase"];
            } elseif ($entry["targetTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["sourceTable"]));
                $targetDb = $entry["sourceDatabase"];
                $fromField = ucfirst($entry["targetField"]);
                $loadField = ucfirst($entry["sourceField"]);
            }
            if ($targetClass == "") {
                continue;
            }
            $dbnameprefix = ucfirst(strtolower($targetDb));
            $targetClassName =  $dbnameprefix . '' . $targetClass;
            if (in_array($targetClassName, $this->seenRelated) == true) {
                continue;
            }

            $this->seenRelated[] = $targetClassName;



            $this->lines[] = 'public function related' . $targetClass . '(?array $limitFields = null): '
                . $targetClassName . '';
            $this->lines[] = '{';
            $this->lines[] = [2];
            $this->lines[] = '$ids = [$this->get' . $fromField . '()];';
            $this->lines[] = '$collection = new ' . $targetClassName . '();';
            $this->lines[] = 'if ($limitFields !== null) {';
            $this->lines[] = [3];
            $this->lines[] = '$collection->limitFields($limitFields);';
            $this->lines[] = [2];
            $this->lines[] = '}';
            $this->lines[] = '$collection->loadFrom' . $loadField . 's($ids);';
            $this->lines[] = 'return $collection;';
            $this->lines[] = [1];
            $this->lines[] = '}';
        }
    }

    protected function createModelFooter(): void
    {
        $this->lines[] = [0];
        $this->lines[] = '}';
        $this->lines[] = '// please do not edit this file';
    }

    protected function createModelSetters(): void
    {
        $this->lines[] = "// Setters";
        foreach ($this->cols as $rowTwo) {
            if ($rowTwo["COLUMN_NAME"] == "id") {
                continue;
            }
            $returnType = "";
            $useType = $this->getColType(
                $rowTwo["DATA_TYPE"],
                $rowTwo["COLUMN_TYPE"],
                $this->workingTable,
                $rowTwo["COLUMN_NAME"]
            );
            if ($useType == "str") {
                $useType = "string";
            }
            $returnType = "?" . $useType . "";
            $this->lines[] = "/**";
            $this->lines[] = "* set" . ucfirst($rowTwo["COLUMN_NAME"]);
            $this->lines[] = "*/";
            $set_function = 'public function set' . ucfirst($rowTwo["COLUMN_NAME"]);
            $set_function .= '(' . $returnType . ' $newValue): UpdateReply';
            $this->lines[] = $set_function;
            $this->lines[] = '{';
            $this->lines[] = [2];
            $this->lines[] = 'return $this->updateField("' . $rowTwo["COLUMN_NAME"] . '", $newValue);';
            $this->lines[] = [1];
            $this->lines[] = '}';
        }
    }

    protected function createModelLoaders(): void
    {
        $this->lines[] = "// Loaders";
        foreach ($this->cols as $rowTwo) {
            if ($rowTwo["COLUMN_NAME"] == "id") {
                continue;
            }
            $useType = $this->getColType(
                $rowTwo["DATA_TYPE"],
                $rowTwo["COLUMN_TYPE"],
                $this->workingTable,
                $rowTwo["COLUMN_NAME"]
            );
            if ($useType == "str") {
                $useType = "string";
            }
            $functionLoadName = 'loadBy' . ucfirst($rowTwo["COLUMN_NAME"]);

            $this->lines[] = 'public function ' . $functionLoadName . '('
                . $useType . ' $' . $rowTwo["COLUMN_NAME"] . '): SingleLoadReply';
            $this->lines[] = '{';
            $this->lines[] = [2];
            $this->lines[] = 'return $this->loadByField(';
            $this->lines[] = [3];
            $this->lines[] = '"' . $rowTwo["COLUMN_NAME"] . '",';
            $this->lines[] = '$' . $rowTwo["COLUMN_NAME"];
            $this->lines[] = [2];
            $this->lines[] =  ');';
            $this->lines[] = [1];
            $this->lines[] = '}';
        }
    }

    protected function createModelGetters(): void
    {
        $this->lines[] = "// Getters";
        foreach ($this->cols as $rowTwo) {
            if ($rowTwo["COLUMN_NAME"] != "id") {
                $returnType = "";
                $useType = $this->getColType(
                    $rowTwo["DATA_TYPE"],
                    $rowTwo["COLUMN_TYPE"],
                    $this->workingTable,
                    $rowTwo["COLUMN_NAME"]
                );
                if ($useType == "str") {
                    $useType = "string";
                }
                $returnType = ": ?" . $useType . "";
                $getFunction = 'public function get' . ucfirst($rowTwo["COLUMN_NAME"]);
                $getFunction .= '()' . $returnType;
                $this->lines[] = $getFunction;
                $this->lines[] = '{';
                $this->lines[] = [2];
                $this->lines[] = 'return $this->getField("' . $rowTwo["COLUMN_NAME"] . '");';
                $this->lines[] = [1];
                $this->lines[] = '}';
            }
        }
    }

    protected function createModelDataset(): void
    {
        $this->lines[] = "// Data Design";
        $this->lines[] = 'protected $fields = [';
        $this->lines[] = [2];
        foreach ($this->cols as $rowTwo) {
            $this->lines[] = '"' . $rowTwo["COLUMN_NAME"] . '",';
        }
        $this->lines[] = [1];
        $this->lines[] = '];';
        $this->lines[] = 'protected $dataset = [';
        $this->lines[] = [2];
        foreach ($this->cols as $rowTwo) {
            $useType = $this->getColType(
                $rowTwo["DATA_TYPE"],
                $rowTwo["COLUMN_TYPE"],
                $this->workingTable,
                $rowTwo["COLUMN_NAME"]
            );
            $detected_default = $rowTwo["COLUMN_DEFAULT"];
            if (($rowTwo["COLUMN_DEFAULT"] == null) || ($rowTwo["COLUMN_DEFAULT"] == "NULL")) {
                $detected_default = "null";
            }
            if ($useType == "str") {
                $detected_default = str_replace("'", "", $detected_default);
                if ((strlen($detected_default) > 0) && ($detected_default !== "null")) {
                    if (strpos($detected_default, '"') === false) {
                        $detected_default = '"' . $detected_default . '"';
                    }
                }
                if ($detected_default == "") {
                    $detected_default = "\'\'";
                }
            }
            $line = '"' . $rowTwo["COLUMN_NAME"] . '" => ["type" => "';
            $line .= $useType . '", "value" => ' . $detected_default . '],';
            $this->lines[] = $line;
        }
        $this->lines[] = [1];
        $this->lines[] = '];';
    }

    protected function createModelHeader(): void
    {
        $dbNameAddon = "";
        if ($this->prefixDb == true) {
            $dbNameAddon = $this->dbName . ".";
        }
        $this->lines[] = '<?php';
        $this->lines[] = '';
        $this->lines[] = 'namespace ' . $this->namespace . ';';
        $this->lines[] = '';
        $this->lines[] = 'use YAPF\Framework\DbObjects\GenClass\GenClass as GenClass;';
        $this->lines[] = 'use YAPF\Framework\Responses\DbObjects\UpdateReply as UpdateReply;';
        $this->lines[] = 'use YAPF\Framework\Responses\DbObjects\SingleLoadReply as SingleLoadReply;';

        $seenused = [];
        foreach ($this->links as $entry) {
            $targetClass = "";
            $targetDb = "";
            if ($entry["sourceTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["targetTable"]));
                $targetDb = $entry["targetDatabase"];
            } elseif ($entry["targetTable"] == $this->workingTable) {
                $targetClass = ucfirst(strtolower($entry["sourceTable"]));
                $targetDb = $entry["sourceDatabase"];
            }
            if ($targetClass == "") {
                continue;
            }
            $targetClassName =  $targetClass;
            if (in_array($targetClassName, $seenused) == true) {
                continue;
            }
            $dbnameprefix = ucfirst(strtolower($targetDb));
            $seenused[] = $targetClassName;
            $namespace = $this->corenamespace;
            $namespace = str_replace("(Set)", "\Set", $namespace);
            $namespace = str_replace("<!DBName!>", $targetDb, $namespace);
            $namespace = str_replace("/", "\\", $namespace);
            $this->lines[] = 'use ' . $namespace . '\\'
            . $targetClass . 'Set as ' . $dbnameprefix . '' . $targetClass . ';';
        }

        $this->lines[] = '';
        $this->lines[] = '// Do not edit this file, rerun gen.php to update!';
        $this->lines[] = 'class ' . $this->className . ' extends genClass';
        $this->lines[] = '{';
        $this->lines[] = [1];
        $this->lines[] = 'protected $use_table = "' . $dbNameAddon . '' . $this->workingTable . '";';
    }
}
